import { getPicksForDate, getLatestPickDate } from "@/lib/db";
import MatchupCard from "@/components/MatchupCard";

export const dynamic = "force-dynamic";

function formatDate(isoDate: string): string {
  const [year, month, day] = isoDate.split("-").map(Number);
  return new Date(year, month - 1, day).toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export default async function HomePage() {
  const date = await getLatestPickDate();

  if (!date) {
    return (
      <main className="max-w-5xl mx-auto px-4 py-16 text-center">
        <Logo />
        <p className="mt-8 text-slate-400 text-lg">
          No picks available yet. Check back soon.
        </p>
      </main>
    );
  }

  const picks = await getPicksForDate(date);

  return (
    <main className="max-w-5xl mx-auto px-4 py-10">
      <Logo />

      <div className="mt-8 mb-6 flex items-center justify-between">
        <h2 className="text-xl font-semibold text-slate-200">
          {formatDate(date)}
        </h2>
        <span className="text-sm text-slate-500">
          {picks.length} game{picks.length !== 1 ? "s" : ""}
        </span>
      </div>

      {picks.length === 0 ? (
        <p className="text-slate-400 text-center py-16">
          No picks for today yet.
        </p>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {picks.map((pick) => (
            <MatchupCard key={pick.id} pick={pick} />
          ))}
        </div>
      )}

      <footer className="mt-16 text-center text-xs text-slate-600">
        Picks generated by ML model · Spreads from DraftKings · For entertainment purposes only
      </footer>
    </main>
  );
}

function Logo() {
  return (
    <div className="flex flex-col items-center gap-1 pt-4">
      <h1 className="text-3xl font-black tracking-tight text-white">
        BetQuity <span className="text-emerald-400">Capital</span>
      </h1>
      <p className="text-sm text-slate-500 tracking-wide uppercase">
        NCAA Men&apos;s Basketball · AI Picks
      </p>
    </div>
  );
}
